name: Track am-dependency dist-tags

on:
  # schedule:
    # - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: dev
            tag: dev
          - branch: staging
            tag: staging
          - branch: master
            tag: prod
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - uses: washogren/auto-update-dependencies@v1
        with:
          package: '@washogren/am-dependency'
          tag: ${{ matrix.tag }}
          base-branch: ${{ matrix.branch }}
          npm-scope: '@washogren'
          token: ${{ secrets.GH_PACKAGES_READ }}
